# Generated by Django 4.0 on 2022-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurls',
            name='urlint',
            field=models.IntegerField(null=True),
        ),
    ]
